namespace Cmf.CustomerPortal.Sdk.Common
{
    public class Resources
    {
        public const string LOGIN_PAT_HELP = "Personal Access Token used to access the Customer Portal";

        public const string DEPLOYMENT_NAME_HELP = "Name of the new Customer Environment. --name is also supported";
        public const string DEPLOYMENT_ALIAS_HELP = "Command Alias";
        public const string DEPLOYMENT_DESCRIPTION_HELP = "Description of the new Customer Environment";
        public const string DEPLOYMENT_PARAMETERSPATH_HELP = "Path to parameters file that describes the Customer Environment";
        public const string DEPLOYMENT_ENVIRONMENTTYPE_HELP = "Type of the Customer Environment to deploy";
        public const string DEPLOYMENT_SITE_HELP = "Name of the Site associated with the Customer Environment";
        public const string DEPLOYMENT_LICENSE_HELP = "Name of the License to use for the Customer Environment";
        public const string DEPLOYMENT_PACKAGE_HELP = "Name of the Deployment Package to use for the Customer Environment";
        public const string DEPLOYMENT_TARGET_HELP = "Name of the Deployment Target to use for the Customer Environment";
        public const string DEPLOYMENT_OUTPUTDIR_HELP = "Directory to place any artifacts generated by the deployment";
        public const string DEPLOYMENT_INTERACTIVE_HELP = "Flag that controls if the user should be prompted to go to the portal to initialize the installation manually";
        public const string DEPLOYMENT_TERMINATE_OTHER_VERSIONS_HELP = "Flag that controls if all the other versions of the Customer Environment should be terminated";

        public const string INFRASTRUCTUREFROMTEMPLATE_NAME_HELP = "The name of the Customer Infrastructure to be created";
        public const string INFRASTRUCTUREFROMTEMPLATE_TEMPLATENAME_HELP = "The name of the Customer Infrastructure template that the new Customer Infrastructure will derive from";
        public const string INFRASTRUCTURE_SITE_HELP = "(deprecated) Name of a Site used to match a Customer with the Customer Infrastructure";
        public const string INFRASTRUCTURE_CUSTOMER_HELP = "Name of the Customer associated with the Customer Infrastructure";
        public const string INFRASTRUCTURE_EXISTING_NAME_HELP = "Name of the existing Customer Infrastructure";
        public const string INFRASTRUCTURE_EXISTING_ENVIRONMENT_TEMPLATE_NAME_HELP = "Name of an existing Customer Environment template that is linked to the Customer Infrastructure";

        public const string GETAGENTCONNECTION_NAME_HELP = "The name of the Infrastructure Agent";

        public const string PUBLISHMANIFESTS_PATH_HELP = "Path to Deployment Package Manifest file, or folder to a folder containing multiple manifest files";

        public const string PUBLISHPACKAGE_PATH_HELP = "Path to Package zip file";

        public const string REPLACETOKENS_HELP = "Replace the tokens specified in the input files using the proper syntax (e.g. #{MyToken}#) with the specified values. E.g. MyToken=value MyToken2=value2.";

        public const string VERBOSE_HELP = "Show detailed logging";
    }
}
