namespace Cmf.CustomerPortal.Sdk.Common
{
    public class Resources
    {
        public const string LOGIN_PAT_HELP = "Personal Access Token used to access the Customer Portal";

        public const string DEPLOYMENT_NAME_HELP = "Name of the new environment";
        public const string DEPLOYMENT_PARAMETERSPATH_HELP = "Path to parameters file that describes the environment";
        public const string DEPLOYMENT_ENVIRONMENTTYPE_HELP = "Type of the environment to deploy";
        public const string DEPLOYMENT_SITE_HELP = "Name of the Site associated with the environment";
        public const string DEPLOYMENT_LICENSE_HELP = "Name of the License to use for the environment";
        public const string DEPLOYMENT_PACKAGE_HELP = "Name of the Deployment Package to use for the environment";
        public const string DEPLOYMENT_TARGET_HELP = "Name of the Deployment Target to use for the environment";
        public const string DEPLOYMENT_OUTPUTDIR_HELP = "Directory to place any artifacts generated by the deployment";

        public const string INFRASTRUCTUREFROMTEMPLATE_NAME_HELP = "The name of the Customer Infrastructure to be created";
        public const string INFRASTRUCTUREFROMTEMPLATE_AGENTNAME_HELP = "The name of the Infrastructure Agent to be linked with the new Customer Infrastructure";
        public const string INFRASTRUCTUREFROMTEMPLATE_TEMPLATENAME_HELP = "The name of the Customer Infrastructure template that the new Customer Infrastructure will derive from";

        public const string GETAGENTCONNECTION_NAME_HELP = "The name of the Infrastructure Agent";

        public const string PUBLISHMANIFESTS_PATH_HELP = "Path to Deployment Package Manifest file, or folder to a folder containing multiple manifest files";

        public const string REPLACETOKENS_HELP = "Replace the tokens specified in the input files using the proper syntax (e.g. #{MyToken}#) with the specified values. E.g. MyToken=value MyToken2=value2.";

        public const string VERBOSE_HELP = "Show detailed logging";
    }
}
