namespace Cmf.CustomerPortal.Sdk.Common;

/// <summary>
/// Help texts for deploying and undeploying Customer Environments and Infrastructure Agents.
/// </summary>
public static partial class Resources
{
    public const string DeploymentNameHelp = "Name of the new Customer Environment. --name is also supported";
    public const string DeploymentAliasHelp = "Command Alias";
    public const string DeploymentDescriptionHelp = "Description of the new Customer Environment";
    public const string DeploymentParametersPathHelp = "Path to parameters file that describes the Customer Environment";
    public const string DeploymentEnvironmentTypeHelp = "Type of the Customer Environment to deploy";
    public const string DeploymentSiteHelp = "Name of the Site associated with the Customer Environment";
    public const string DeploymentLicensesHelp = "Comma-separated names of the Licenses' Unique Name";
    public const string DeploymentPackageHelp = "Name of the Deployment Package to use for the Customer Environment";
    public const string DeploymentTargetHelp = "Name of the Deployment Target to use for the Customer Environment";
    public const string DeploymentOutputDirHelp = "Directory to place any artifacts generated by the deployment";
    public const string DeploymentInteractiveHelp = "Flag that controls if the user should be prompted to go to the portal to initialize the installation manually";
    public const string DeploymentTerminateOtherVersionsHelp = "Flag that controls if all the other versions of the Customer Environment should be terminated";
    public const string DeploymentTimeoutMinutesHelp = "Timeout, in minutes, that are allowed to wait for the deployment to succeed. The default is 360 minutes (6 hours).";
    public const string DeploymentTimeoutMinutesToGetSomeMBMessageHelp = "Timeout, in minutes, that the SDK client waits to receive any message from the portal via Message Bus. The default is 30 minutes.";
    public const string DeploymentTerminateOtherVersionsRemoveHelp = "Flag that controls if the deployments of the versions of the Customer Environment that will be terminated should be removed. Requires the terminateOtherVersions flag.";
    public const string DeploymentTerminateOtherVersionsRemoveVolumesHelp = "Flag that controls if the volumes of the versions of the Customer Environment that will be terminated should be removed. Requires the terminateOtherVersions and terminateOtherVersionsRemove flags.";

    public const string UndeploymentForceHelp = "Flag that controls if the confirmation message on whether to proceed with undeployment is skipped.";
}
